//! Underlying data for parsing IPA.
//!
//! None of this is guaranteed to be stable across versions, and some of it may be incomplete or inaccurate. Use with caution.

/// All phonemes with their features. This list is not guaranteed to be stable across versions.
pub static PHONEMES: &[(&str, &[crate::Feature])] = {
    use crate::ConsonantFeature::*;
    use crate::Depth::*;
    use crate::Feature::*;
    use crate::Height::*;
    use crate::Manner::*;
    use crate::Place::*;
    use crate::VowelFeature::*;
    use crate::feature::Airstream::*;
    use crate::feature::RearArticulation;
    use crate::feature::FricativeKind::*;


    // must be ordered longest to shortest, otherwise the longest match will be missed
    &[
        // 2-char affricates with over-tie
        (
            "p͡ɸ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "b͡β",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "p͡f",
            &[
                Consonant(Place(Labiodental)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "b͡v",
            &[
                Consonant(Place(Labiodental)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "t̪͡θ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "t͡θ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "d͡ð",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "d̪͡ð",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "t͡s",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Affricate(Sibilant))),
            ],
        ),
        (
            "d͡z",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Affricate(Sibilant))),
                Consonant(Voiced),
            ],
        ),
        (
            "t͡ɬ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Affricate(NonSibilant(Lateral)))),
            ],
        ),
        (
            "d͡ɮ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Affricate(NonSibilant(Lateral)))),
                Consonant(Voiced),
            ],
        ),
        (
            "t͡ʃ",
            &[
                Consonant(Place(PostAlveolar)),
                Consonant(Manner(Affricate(Sibilant))),
            ],
        ),
        (
            "d͡ʒ",
            &[
                Consonant(Place(PostAlveolar)),
                Consonant(Manner(Affricate(Sibilant))),
                Consonant(Voiced),
            ],
        ),
        (
            "t͡ɕ",
            &[
                Consonant(Place(Alveolopalatal)),
                Consonant(Manner(Affricate(Sibilant))),
            ],
        ),
        (
            "d͡ʑ",
            &[
                Consonant(Place(Alveolopalatal)),
                Consonant(Manner(Affricate(Sibilant))),
                Consonant(Voiced),
            ],
        ),
        (
            "ȶ͡ɕ",
            &[
                Consonant(Place(Alveolopalatal)),
                Consonant(Manner(Affricate(Sibilant))),
            ],
        ),
        (
            "ȡ͡ʑ",
            &[
                Consonant(Place(Alveolopalatal)),
                Consonant(Manner(Affricate(Sibilant))),
                Consonant(Voiced),
            ],
        ),
        (
            "ʈ͡ʂ",
            &[
                Consonant(Place(Retroflex)),
                Consonant(Manner(Affricate(Sibilant))),
            ],
        ),
        (
            "ɖ͡ʐ",
            &[
                Consonant(Place(Retroflex)),
                Consonant(Manner(Affricate(Sibilant))),
                Consonant(Voiced),
            ],
        ),
        (
            "ʈ͡ꞎ",
            &[
                Consonant(Place(Retroflex)),
                Consonant(Manner(Affricate(NonSibilant(Lateral)))),
            ],
        ),
        (
            "ɖ͡𝼅",
            &[
                Consonant(Place(Retroflex)),
                Consonant(Manner(Affricate(NonSibilant(Lateral)))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɖ͡ɭ˔",
            &[
                Consonant(Place(Retroflex)),
                Consonant(Manner(Affricate(NonSibilant(Lateral)))),
                Consonant(Voiced),
            ],
        ),
        (
            "c͡ç",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "ɟ͡ʝ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "k͡x",
            &[
                Consonant(Place(Velar)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "g͡ɣ",
            &[
                Consonant(Place(Velar)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "q͡χ",
            &[
                Consonant(Place(Uvular)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "ɢ͡ʁ",
            &[
                Consonant(Place(Uvular)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        // epiglottal affricates with over-tie
        (
            "ʡ͡ʜ",
            &[
                Consonant(Place(Epiglottal)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "ʡ͡ʢ",
            &[
                Consonant(Place(Epiglottal)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        // glottal affricate with over-tie
        (
            "ʔ͡h",
            &[
                Consonant(Place(Glottal)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        // palatal lateral affricates with over-tie
        (
            "c͡𝼆",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Affricate(NonSibilant(Lateral)))),
            ],
        ),
        (
            "ɟ͡ʎ̝",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Affricate(NonSibilant(Lateral)))),
                Consonant(Voiced),
            ],
        ),
        // velar lateral affricates with over-tie
        (
            "k͡𝼄",
            &[Consonant(Place(Velar)), Consonant(Manner(Affricate(NonSibilant(Lateral))))],
        ),
        (
            "ɡ͡ʟ̝",
            &[
                Consonant(Place(Velar)),
                Consonant(Manner(Affricate(NonSibilant(Lateral)))),
                Consonant(Voiced),
            ],
        ),
        // click consonants with over-tie — velar accompaniment
        (
            "k͡ʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡ͡ʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ͡ʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "k͡ǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡ͡ǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ͡ǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "k͡ǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡ͡ǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ͡ǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "k͡ǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡ͡ǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ͡ǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "k͡ǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡ͡ǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ͡ǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        // click consonants with over-tie — velar accompaniment (alternate transcriptions)
        (
            "k͡ʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡ͡ʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ͡ʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "k͡𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡ͡𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ͡𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "k͡ʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡ͡ʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ͡ʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "k͡ʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡ͡ʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ͡ʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        // click consonants with over-tie — uvular accompaniment
        (
            "q͡ʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢ͡ʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ͡ʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "q͡ǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢ͡ǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ͡ǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "q͡ǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢ͡ǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ͡ǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "q͡ǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢ͡ǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ͡ǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "q͡ǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢ͡ǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ͡ǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        // click consonants with over-tie — uvular accompaniment (alternate transcriptions)
        (
            "q͡ʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢ͡ʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ͡ʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "q͡𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢ͡𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ͡𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "q͡ʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢ͡ʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ͡ʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "q͡ʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢ͡ʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ͡ʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        // 2-char affricates with under-tie
        (
            "p͜ɸ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "b͜β",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "p͜f",
            &[
                Consonant(Place(Labiodental)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "b͜v",
            &[
                Consonant(Place(Labiodental)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "t͜θ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "t̪͜θ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "d͜ð",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "d̪͜ð",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "t͜s",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Affricate(Sibilant))),
            ],
        ),
        (
            "d͜z",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Affricate(Sibilant))),
                Consonant(Voiced),
            ],
        ),
        (
            "t͜ʃ",
            &[
                Consonant(Place(PostAlveolar)),
                Consonant(Manner(Affricate(Sibilant))),
            ],
        ),
        (
            "d͜ʒ",
            &[
                Consonant(Place(PostAlveolar)),
                Consonant(Manner(Affricate(Sibilant))),
                Consonant(Voiced),
            ],
        ),
        (
            "t͜ɕ",
            &[
                Consonant(Place(Alveolopalatal)),
                Consonant(Manner(Affricate(Sibilant))),
            ],
        ),
        (
            "d͜ʑ",
            &[
                Consonant(Place(Alveolopalatal)),
                Consonant(Manner(Affricate(Sibilant))),
                Consonant(Voiced),
            ],
        ),
        (
            "ȶ͜ɕ",
            &[
                Consonant(Place(Alveolopalatal)),
                Consonant(Manner(Affricate(Sibilant))),
            ],
        ),
        (
            "ȡ͜ʑ",
            &[
                Consonant(Place(Alveolopalatal)),
                Consonant(Manner(Affricate(Sibilant))),
                Consonant(Voiced),
            ],
        ),
        (
            "ʈ͜ʂ",
            &[
                Consonant(Place(Retroflex)),
                Consonant(Manner(Affricate(Sibilant))),
            ],
        ),
        (
            "ɖ͜ʐ",
            &[
                Consonant(Place(Retroflex)),
                Consonant(Manner(Affricate(Sibilant))),
                Consonant(Voiced),
            ],
        ),
        (
            "c͜ç",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "ɟ͜ʝ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "k͜x",
            &[
                Consonant(Place(Velar)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "g͜ɣ",
            &[
                Consonant(Place(Velar)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "q͜χ",
            &[
                Consonant(Place(Uvular)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "ɢ͜ʁ",
            &[
                Consonant(Place(Uvular)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        // epiglottal affricates with under-tie
        (
            "ʡ͜ʜ",
            &[
                Consonant(Place(Epiglottal)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "ʡ͜ʢ",
            &[
                Consonant(Place(Epiglottal)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        // glottal affricate with under-tie
        (
            "ʔ͜h",
            &[
                Consonant(Place(Glottal)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        // palatal lateral affricates with under-tie
        (
            "c͜𝼆",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Affricate(NonSibilant(Lateral)))),
            ],
        ),
        (
            "ɟ͜ʎ̝",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Affricate(NonSibilant(Lateral)))),
                Consonant(Voiced),
            ],
        ),
        // velar lateral affricates with under-tie
        (
            "k͜𝼄",
            &[Consonant(Place(Velar)), Consonant(Manner(Affricate(NonSibilant(Lateral))))],
        ),
        (
            "ɡ͜ʟ̝",
            &[
                Consonant(Place(Velar)),
                Consonant(Manner(Affricate(NonSibilant(Lateral)))),
                Consonant(Voiced),
            ],
        ),
        // click consonants with under-tie — velar accompaniment
        (
            "k͜ʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡ͜ʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ͜ʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "k͜ǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡ͜ǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ͜ǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "k͜ǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡ͜ǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ͜ǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "k͜ǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡ͜ǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ͜ǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "k͜ǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡ͜ǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ͜ǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        // click consonants with under-tie — velar accompaniment (alternate transcriptions)
        (
            "k͜ʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡ͜ʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ͜ʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "k͜𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡ͜𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ͜𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "k͜ʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡ͜ʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ͜ʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "k͜ʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡ͜ʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ͜ʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        // click consonants with under-tie — uvular accompaniment
        (
            "q͜ʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢ͜ʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ͜ʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "q͜ǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢ͜ǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ͜ǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "q͜ǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢ͜ǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ͜ǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "q͜ǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢ͜ǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ͜ǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "q͜ǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢ͜ǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ͜ǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        // click consonants with under-tie — uvular accompaniment (alternate transcriptions)
        (
            "q͜ʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢ͜ʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ͜ʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "q͜𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢ͜𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ͜𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "q͜ʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢ͜ʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ͜ʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "q͜ʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢ͜ʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ͜ʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        // 2-char affricates
        (
            "pɸ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "bβ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "pf",
            &[
                Consonant(Place(Labiodental)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "bv",
            &[
                Consonant(Place(Labiodental)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "tθ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "t̪θ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "d̪ð",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "ts",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Affricate(Sibilant))),
            ],
        ),
        (
            "dz",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Affricate(Sibilant))),
                Consonant(Voiced),
            ],
        ),
        (
            "tʃ",
            &[
                Consonant(Place(PostAlveolar)),
                Consonant(Manner(Affricate(Sibilant))),
            ],
        ),
        (
            "dʒ",
            &[
                Consonant(Place(PostAlveolar)),
                Consonant(Manner(Affricate(Sibilant))),
                Consonant(Voiced),
            ],
        ),
        (
            "tɕ",
            &[
                Consonant(Place(Alveolopalatal)),
                Consonant(Manner(Affricate(Sibilant))),
            ],
        ),
        (
            "dʑ",
            &[
                Consonant(Place(Alveolopalatal)),
                Consonant(Manner(Affricate(Sibilant))),
                Consonant(Voiced),
            ],
        ),
        (
            "ȶɕ",
            &[
                Consonant(Place(Alveolopalatal)),
                Consonant(Manner(Affricate(Sibilant))),
            ],
        ),
        (
            "ȡʑ",
            &[
                Consonant(Place(Alveolopalatal)),
                Consonant(Manner(Affricate(Sibilant))),
                Consonant(Voiced),
            ],
        ),
        (
            "ʈʂ",
            &[
                Consonant(Place(Retroflex)),
                Consonant(Manner(Affricate(Sibilant))),
            ],
        ),
        (
            "ɖʐ",
            &[
                Consonant(Place(Retroflex)),
                Consonant(Manner(Affricate(Sibilant))),
                Consonant(Voiced),
            ],
        ),
        (
            "cç",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "ɟʝ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "kx",
            &[
                Consonant(Place(Velar)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "gɣ",
            &[
                Consonant(Place(Velar)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "qχ",
            &[
                Consonant(Place(Uvular)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "ɢʁ",
            &[
                Consonant(Place(Uvular)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        // epiglottal affricates (no tie bar)
        (
            "ʡʜ",
            &[
                Consonant(Place(Epiglottal)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        (
            "ʡʢ",
            &[
                Consonant(Place(Epiglottal)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        // glottal affricate (no tie bar)
        (
            "ʔh",
            &[
                Consonant(Place(Glottal)),
                Consonant(Manner(Affricate(NonSibilant(Median)))),
            ],
        ),
        // click consonants (no tie bar) — velar accompaniment
        (
            "kʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "kǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "kǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "kǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "kǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        // click consonants (no tie bar) — uvular accompaniment
        (
            "qʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "qǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "qǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "qǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "qǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        // click consonants (no tie bar) — velar accompaniment (alternate transcriptions)
        (
            "kʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "k𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡ𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "kʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "kʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ɡʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        // click consonants (no tie bar) — uvular accompaniment (alternate transcriptions)
        (
            "qʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "q𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢ𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "qʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "qʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
            ],
        ),
        (
            "ɢʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Uvular))),
                Consonant(Voiced),
            ],
        ),
        // bilabial
        (
            "m",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Nasal)),
                Consonant(Voiced),
            ],
        ),
        ("p", &[Consonant(Place(Bilabial)), Consonant(Manner(Stop))]),
        (
            "b",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Stop)),
                Consonant(Voiced),
            ],
        ),
        (
            "ɸ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Fricative(NonSibilant(Median)))),
            ],
        ),
        (
            "β",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Fricative(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "ʙ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Trill)),
                Consonant(Voiced),
            ],
        ),
        (
            "ⱱ̟",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Flap(Median))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɓ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Implosive)),
                Consonant(Voiced),
            ],
        ),
        // labiodental
        (
            "ɱ",
            &[
                Consonant(Place(Labiodental)),
                Consonant(Manner(Nasal)),
                Consonant(Voiced),
            ],
        ),
        (
            "f",
            &[
                Consonant(Place(Labiodental)),
                Consonant(Manner(Fricative(NonSibilant(Median)))),
            ],
        ),
        (
            "v",
            &[
                Consonant(Place(Labiodental)),
                Consonant(Manner(Fricative(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "ʋ",
            &[
                Consonant(Place(Labiodental)),
                Consonant(Manner(Approximant(Median))),
                Consonant(Voiced),
            ],
        ),
        (
            "ⱱ",
            &[
                Consonant(Place(Labiodental)),
                Consonant(Manner(Flap(Median))),
                Consonant(Voiced),
            ],
        ),
        // dental
        (
            "θ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Fricative(NonSibilant(Median)))),
            ],
        ),
        (
            "ð",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Fricative(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        // alveolar
        (
            "n",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Nasal)),
                Consonant(Voiced),
            ],
        ),
        ("t", &[Consonant(Place(Alveolar)), Consonant(Manner(Stop))]),
        (
            "d",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Stop)),
                Consonant(Voiced),
            ],
        ),
        (
            "s",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Fricative(Sibilant))),
            ],
        ),
        (
            "z",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Fricative(Sibilant))),
                Consonant(Voiced),
            ],
        ),
        (
            "ʃ",
            &[
                Consonant(Place(PostAlveolar)),
                Consonant(Manner(Fricative(Sibilant))),
            ],
        ),
        (
            "ʒ",
            &[
                Consonant(Place(PostAlveolar)),
                Consonant(Manner(Fricative(Sibilant))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɬ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Fricative(NonSibilant(Lateral)))),
            ],
        ),
        (
            "ɮ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Fricative(NonSibilant(Lateral)))),
                Consonant(Voiced),
            ],
        ),
        (
            "r",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Trill)),
                Consonant(Voiced),
            ],
        ),
        (
            "ɾ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Flap(Median))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɹ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Approximant(Median))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɺ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Flap(Lateral))),
                Consonant(Voiced),
            ],
        ),
        (
            "l",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Approximant(Lateral))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɫ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Approximant(Lateral))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Implosive)),
                Consonant(Voiced),
            ],
        ),
        // alveolopalatal
        (
            "ȶ",
            &[Consonant(Place(Alveolopalatal)), Consonant(Manner(Stop))],
        ),
        (
            "ȡ",
            &[
                Consonant(Place(Alveolopalatal)),
                Consonant(Manner(Stop)),
                Consonant(Voiced),
            ],
        ),
        (
            "ȵ",
            &[
                Consonant(Place(Alveolopalatal)),
                Consonant(Manner(Nasal)),
                Consonant(Voiced),
            ],
        ),
        (
            "ɕ",
            &[
                Consonant(Place(Alveolopalatal)),
                Consonant(Manner(Fricative(Sibilant))),
            ],
        ),
        (
            "ʑ",
            &[
                Consonant(Place(Alveolopalatal)),
                Consonant(Manner(Fricative(Sibilant))),
                Consonant(Voiced),
            ],
        ),
        (
            "ȴ",
            &[
                Consonant(Place(Alveolopalatal)),
                Consonant(Manner(Approximant(Lateral))),
                Consonant(Voiced),
            ],
        ),
        // retroflex
        ("ʈ", &[Consonant(Place(Retroflex)), Consonant(Manner(Stop))]),
        (
            "ɖ",
            &[
                Consonant(Place(Retroflex)),
                Consonant(Manner(Stop)),
                Consonant(Voiced),
            ],
        ),
        (
            "ɳ",
            &[
                Consonant(Place(Retroflex)),
                Consonant(Manner(Nasal)),
                Consonant(Voiced),
            ],
        ),
        (
            "ʂ",
            &[
                Consonant(Place(Retroflex)),
                Consonant(Manner(Fricative(Sibilant))),
            ],
        ),
        (
            "ʐ",
            &[
                Consonant(Place(Retroflex)),
                Consonant(Manner(Fricative(Sibilant))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɽ",
            &[
                Consonant(Place(Retroflex)),
                Consonant(Manner(Flap(Median))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɻ",
            &[
                Consonant(Place(Retroflex)),
                Consonant(Manner(Approximant(Median))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɭ",
            &[
                Consonant(Place(Retroflex)),
                Consonant(Manner(Approximant(Lateral))),
                Consonant(Voiced),
            ],
        ),
        (
            "ꞎ",
            &[
                Consonant(Place(Retroflex)),
                Consonant(Manner(Fricative(NonSibilant(Lateral)))),
            ],
        ),
        (
            "ᶑ",
            &[
                Consonant(Place(Retroflex)),
                Consonant(Manner(Implosive)),
                Consonant(Voiced),
            ],
        ),
        // palatal
        ("c", &[Consonant(Place(Palatal)), Consonant(Manner(Stop))]),
        (
            "ɟ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Stop)),
                Consonant(Voiced),
            ],
        ),
        (
            "ɲ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Nasal)),
                Consonant(Voiced),
            ],
        ),
        (
            "ç",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Fricative(NonSibilant(Median)))),
            ],
        ),
        (
            "ʝ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Fricative(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "ʎ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Approximant(Lateral))),
                Consonant(Voiced),
            ],
        ),
        (
            "j",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Approximant(Median))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɥ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Approximant(Median))),
                Consonant(Voiced),
            ],
        ),
        (
            "𝼆",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Fricative(NonSibilant(Lateral)))),
            ],
        ),
        (
            "ʎ̝",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Fricative(NonSibilant(Lateral)))),
                Consonant(Voiced),
            ],
        ),
        (
            "ʄ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Implosive)),
                Consonant(Voiced),
            ],
        ),
        // velar
        ("k", &[Consonant(Place(Velar)), Consonant(Manner(Stop))]),
        (
            "g",
            &[
                Consonant(Place(Velar)),
                Consonant(Manner(Stop)),
                Consonant(Voiced),
            ],
        ),
        (
            "ŋ",
            &[
                Consonant(Place(Velar)),
                Consonant(Manner(Nasal)),
                Consonant(Voiced),
            ],
        ),
        (
            "x",
            &[
                Consonant(Place(Velar)),
                Consonant(Manner(Fricative(NonSibilant(Median)))),
            ],
        ),
        (
            "ɣ",
            &[
                Consonant(Place(Velar)),
                Consonant(Manner(Fricative(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "w",
            &[
                Consonant(Place(Velar)),
                Consonant(Manner(Approximant(Median))),
                Consonant(Voiced),
            ],
        ),
        (
            "ʍ",
            &[
                Consonant(Place(Velar)),
                Consonant(Manner(Approximant(Median))),
            ],
        ),
        (
            "ɰ",
            &[
                Consonant(Place(Velar)),
                Consonant(Manner(Approximant(Median))),
                Consonant(Voiced),
            ],
        ),
        (
            "ʟ",
            &[
                Consonant(Place(Velar)),
                Consonant(Manner(Approximant(Lateral))),
                Consonant(Voiced),
            ],
        ),
        (
            "𝼄",
            &[Consonant(Place(Velar)), Consonant(Manner(Fricative(NonSibilant(Lateral))))],
        ),
        (
            "ʟ̝",
            &[
                Consonant(Place(Velar)),
                Consonant(Manner(Fricative(NonSibilant(Lateral)))),
                Consonant(Voiced),
            ],
        ),
        (
            "ʟ̆",
            &[
                Consonant(Place(Velar)),
                Consonant(Manner(Flap(Lateral))),
                Consonant(Voiced),
            ],
        ),
        (
            "ɠ",
            &[
                Consonant(Place(Velar)),
                Consonant(Manner(Implosive)),
                Consonant(Voiced),
            ],
        ),
        // uvular
        ("q", &[Consonant(Place(Uvular)), Consonant(Manner(Stop))]),
        (
            "ɢ",
            &[
                Consonant(Place(Uvular)),
                Consonant(Manner(Stop)),
                Consonant(Voiced),
            ],
        ),
        (
            "ɴ",
            &[
                Consonant(Place(Uvular)),
                Consonant(Manner(Nasal)),
                Consonant(Voiced),
            ],
        ),
        (
            "χ",
            &[
                Consonant(Place(Uvular)),
                Consonant(Manner(Fricative(NonSibilant(Median)))),
            ],
        ),
        (
            "ʁ",
            &[
                Consonant(Place(Uvular)),
                Consonant(Manner(Fricative(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        (
            "ʀ",
            &[
                Consonant(Place(Uvular)),
                Consonant(Manner(Trill)),
                Consonant(Voiced),
            ],
        ),
        (
            "ʛ",
            &[
                Consonant(Place(Uvular)),
                Consonant(Manner(Implosive)),
                Consonant(Voiced),
            ],
        ),
        // pharyngeal
        (
            "ħ",
            &[
                Consonant(Place(Pharyngeal)),
                Consonant(Manner(Fricative(NonSibilant(Median)))),
            ],
        ),
        (
            "ʕ",
            &[
                Consonant(Place(Pharyngeal)),
                Consonant(Manner(Fricative(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        // epiglottal
        (
            "ʡ",
            &[Consonant(Place(Epiglottal)), Consonant(Manner(Stop))],
        ),
        (
            "ʜ",
            &[Consonant(Place(Epiglottal)), Consonant(Manner(Trill))],
        ),
        (
            "ʢ",
            &[
                Consonant(Place(Epiglottal)),
                Consonant(Manner(Trill)),
                Consonant(Voiced),
            ],
        ),
        // glottal
        ("ʔ", &[Consonant(Place(Glottal)), Consonant(Manner(Stop))]),
        (
            "h",
            &[
                Consonant(Place(Glottal)),
                Consonant(Manner(Fricative(NonSibilant(Median)))),
            ],
        ),
        (
            "ɦ",
            &[
                Consonant(Place(Glottal)),
                Consonant(Manner(Fricative(NonSibilant(Median)))),
                Consonant(Voiced),
            ],
        ),
        // clicks (bare symbols, default to velar rear articulation)
        (
            "ʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "𝼊",
            &[
                Consonant(Place(Retroflex)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        // alternate click transcriptions
        (
            "ʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        // click consonants with superscript prefix — velar accompaniment
        (
            "ᵏʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ᵍʘ",
            &[
                Consonant(Place(Bilabial)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ᵏǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ᵍǀ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ᵏǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ᵍǃ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ᵏǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ᵍǂ",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ᵏǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ᵍǁ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ᵏʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ᵍʇ",
            &[
                Consonant(Place(Dental)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ᵏ𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ᵍ𝼋",
            &[
                Consonant(Place(Palatal)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ᵏʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ᵍʗ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        (
            "ᵏʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
            ],
        ),
        (
            "ᵍʖ",
            &[
                Consonant(Place(Alveolar)),
                Consonant(Manner(Click(RearArticulation::Velar))),
                Consonant(Voiced),
            ],
        ),
        // close vowels
        ("i", &[Vowel(Height(Close)), Vowel(Depth(Front))]),
        (
            "y",
            &[Vowel(Height(Close)), Vowel(Depth(Front)), Vowel(Rounded)],
        ),
        ("ɨ", &[Vowel(Height(Close)), Vowel(Depth(Central))]),
        (
            "ʉ",
            &[Vowel(Height(Close)), Vowel(Depth(Central)), Vowel(Rounded)],
        ),
        ("ɯ", &[Vowel(Height(Close)), Vowel(Depth(Back))]),
        (
            "u",
            &[Vowel(Height(Close)), Vowel(Depth(Back)), Vowel(Rounded)],
        ),
        // near-close vowels
        ("ɪ", &[Vowel(Height(NearClose)), Vowel(Depth(NearFront))]),
        (
            "ʏ",
            &[
                Vowel(Height(NearClose)),
                Vowel(Depth(NearFront)),
                Vowel(Rounded),
            ],
        ),
        (
            "ʊ",
            &[
                Vowel(Height(NearClose)),
                Vowel(Depth(NearBack)),
                Vowel(Rounded),
            ],
        ),
        // close-mid vowels
        ("e", &[Vowel(Height(CloseMid)), Vowel(Depth(Front))]),
        (
            "ø",
            &[Vowel(Height(CloseMid)), Vowel(Depth(Front)), Vowel(Rounded)],
        ),
        ("ɘ", &[Vowel(Height(CloseMid)), Vowel(Depth(Central))]),
        (
            "ɵ",
            &[
                Vowel(Height(CloseMid)),
                Vowel(Depth(Central)),
                Vowel(Rounded),
            ],
        ),
        ("ɤ", &[Vowel(Height(CloseMid)), Vowel(Depth(Back))]),
        (
            "o",
            &[Vowel(Height(CloseMid)), Vowel(Depth(Back)), Vowel(Rounded)],
        ),
        // mid vowels
        ("ə", &[Vowel(Height(Mid)), Vowel(Depth(Central))]),
        // open-mid vowels
        ("ɛ", &[Vowel(Height(OpenMid)), Vowel(Depth(Front))]),
        (
            "œ",
            &[Vowel(Height(OpenMid)), Vowel(Depth(Front)), Vowel(Rounded)],
        ),
        ("ɜ", &[Vowel(Height(OpenMid)), Vowel(Depth(Central))]),
        (
            "ɞ",
            &[
                Vowel(Height(OpenMid)),
                Vowel(Depth(Central)),
                Vowel(Rounded),
            ],
        ),
        ("ʌ", &[Vowel(Height(OpenMid)), Vowel(Depth(Back))]),
        (
            "ɔ",
            &[Vowel(Height(OpenMid)), Vowel(Depth(Back)), Vowel(Rounded)],
        ),
        // near-open vowels
        ("æ", &[Vowel(Height(NearOpen)), Vowel(Depth(Front))]),
        ("ɐ", &[Vowel(Height(NearOpen)), Vowel(Depth(Central))]),
        // open vowels
        ("a", &[Vowel(Height(Open)), Vowel(Depth(Front))]),
        (
            "ɶ",
            &[Vowel(Height(Open)), Vowel(Depth(Front)), Vowel(Rounded)],
        ),
        ("ä", &[Vowel(Height(Open)), Vowel(Depth(Central))]),
        ("ɑ", &[Vowel(Height(Open)), Vowel(Depth(Back))]),
        (
            "ɒ",
            &[Vowel(Height(Open)), Vowel(Depth(Back)), Vowel(Rounded)],
        ),
    ]
};

/// See <https://en.wikipedia.org/wiki/Diphthong> / <https://en.wikipedia.org/wiki/Triphthong>.
/// This list is not guaranteed to be stable across versions.
pub static POLYPHTHONG_COMPONENTS: &[(&str, &[crate::Feature])] = {
    use crate::Depth::*;
    use crate::Feature::*;
    use crate::Height::*;
    use crate::VowelFeature::*;

    &[
        // close vowels
        ("i̯", &[Vowel(Height(Close)), Vowel(Depth(Front))]),
        (
            "y̯",
            &[Vowel(Height(Close)), Vowel(Depth(Front)), Vowel(Rounded)],
        ),
        ("ɨ̯", &[Vowel(Height(Close)), Vowel(Depth(Central))]),
        (
            "ʉ̯",
            &[Vowel(Height(Close)), Vowel(Depth(Central)), Vowel(Rounded)],
        ),
        ("ɯ̯", &[Vowel(Height(Close)), Vowel(Depth(Back))]),
        (
            "u̯",
            &[Vowel(Height(Close)), Vowel(Depth(Back)), Vowel(Rounded)],
        ),
        // near-close vowels
        ("ɪ̯", &[Vowel(Height(NearClose)), Vowel(Depth(NearFront))]),
        (
            "ʏ̯",
            &[
                Vowel(Height(NearClose)),
                Vowel(Depth(NearFront)),
                Vowel(Rounded),
            ],
        ),
        (
            "ʊ̯",
            &[
                Vowel(Height(NearClose)),
                Vowel(Depth(NearBack)),
                Vowel(Rounded),
            ],
        ),
        // close-mid vowels
        ("e̯", &[Vowel(Height(CloseMid)), Vowel(Depth(Front))]),
        (
            "ø̯",
            &[Vowel(Height(CloseMid)), Vowel(Depth(Front)), Vowel(Rounded)],
        ),
        ("ɘ̯", &[Vowel(Height(CloseMid)), Vowel(Depth(Central))]),
        (
            "ɵ̯",
            &[
                Vowel(Height(CloseMid)),
                Vowel(Depth(Central)),
                Vowel(Rounded),
            ],
        ),
        ("ɤ̯", &[Vowel(Height(CloseMid)), Vowel(Depth(Back))]),
        (
            "o̯",
            &[Vowel(Height(CloseMid)), Vowel(Depth(Back)), Vowel(Rounded)],
        ),
        // mid vowels
        ("ə̯", &[Vowel(Height(Mid)), Vowel(Depth(Central))]),
        // open-mid vowels
        ("ɛ̯", &[Vowel(Height(OpenMid)), Vowel(Depth(Front))]),
        (
            "œ̯",
            &[Vowel(Height(OpenMid)), Vowel(Depth(Front)), Vowel(Rounded)],
        ),
        ("ɜ̯", &[Vowel(Height(OpenMid)), Vowel(Depth(Central))]),
        (
            "ɞ̯",
            &[
                Vowel(Height(OpenMid)),
                Vowel(Depth(Central)),
                Vowel(Rounded),
            ],
        ),
        ("ʌ̯", &[Vowel(Height(OpenMid)), Vowel(Depth(Back))]),
        (
            "ɔ̯",
            &[Vowel(Height(OpenMid)), Vowel(Depth(Back)), Vowel(Rounded)],
        ),
        // near-open vowels
        ("æ̯", &[Vowel(Height(NearOpen)), Vowel(Depth(Front))]),
        ("ɐ̯", &[Vowel(Height(NearOpen)), Vowel(Depth(Central))]),
        // open vowels
        ("a̯", &[Vowel(Height(Open)), Vowel(Depth(Front))]),
        (
            "ɶ̯",
            &[Vowel(Height(Open)), Vowel(Depth(Front)), Vowel(Rounded)],
        ),
        ("ä̯", &[Vowel(Height(Open)), Vowel(Depth(Central))]),
        ("ɑ̯", &[Vowel(Height(Open)), Vowel(Depth(Back))]),
        (
            "ɒ̯",
            &[Vowel(Height(Open)), Vowel(Depth(Back)), Vowel(Rounded)],
        ),
    ]
};

/// Modifiers which appear before the base character. This list is not guaranteed to be stable across versions.
pub static PREFIX_MODIFIERS: &[(&str, crate::Modifier)] = {
    use crate::Modifier::*;

    &[
        ("m͜", PreNasalized),
        ("n͜", PreNasalized),
        ("ɳ͜", PreNasalized),
        ("ɲ͜", PreNasalized),
        ("ŋ͜", PreNasalized),
        ("ɴ͜", PreNasalized),
        ("ᵐ", PreNasalized),
        ("ⁿ", PreNasalized),
        ("ᶯ", PreNasalized),
        ("ᶮ", PreNasalized),
        ("ᵑ", PreNasalized),
        ("ᶰ", PreNasalized),
        ("ᵇ", PreStopped),
        ("ᵈ", PreStopped),
        ("ᶡ", PreStopped),
        ("ᶢ", PreStopped),
        ("ᵖ", PreStopped),
        ("ᵗ", PreStopped),
        ("ᶜ", PreStopped),
        ("ᵏ", PreStopped),
        ("ʰ", PreAspirated),
        ("ˣ", VelarFricativeOnset),
    ]
};

/// Modifiers which appear after the base character. This list is not guaranteed to be stable across versions.
pub static POSTFIX_MODIFIERS: &[(&str, crate::Modifier)] = {
    use crate::Modifier::*;

    &[
        ("̯", NonSyllabic),
        ("̑", NonSyllabic),
        ("̩", Syllabic),
        ("̍", Syllabic),
        ("ʰ", Aspirated),
        ("̚", Release(crate::feature::Release::None)),
        ("ⁿ", Release(crate::feature::Release::Nasal)),
        ("ᵇ", PostStopped),
        ("ᵈ", PostStopped),
        ("ᶡ", PostStopped),
        ("ᶢ", PostStopped),
        ("ᵖ", PostStopped),
        ("ᵗ", PostStopped),
        ("ᶜ", PostStopped),
        ("ᵏ", PostStopped),
        ("ᶿ", Release(crate::feature::Release::DentalFricative)),
        ("ˡ", Release(crate::feature::Release::Lateral)),
        ("ˣ", Release(crate::feature::Release::VelarFricative)),
        ("ᵊ", Release(crate::feature::Release::Schwa)),
        ("̥", Voice(crate::feature::Voice::Voiceless)),
        ("̊", Voice(crate::feature::Voice::Voiceless)),
        ("̬", Voice(crate::feature::Voice::Voiced)),
        ("̤", Voice(crate::feature::Voice::Breathy)),
        ("̰", Voice(crate::feature::Voice::Creaky)),
        ("̪", Dental),
        ("͆", Dental),
        ("̼", Linguolabial),
        ("̺", Apical),
        ("̻", Laminal),
        (
            "̟",
            RelativeArticulation(crate::feature::RelativeArticulation::Advanced),
        ),
        (
            "̠",
            RelativeArticulation(crate::feature::RelativeArticulation::Retracted),
        ),
        (
            "˖",
            RelativeArticulation(crate::feature::RelativeArticulation::Advanced),
        ),
        (
            "˗",
            RelativeArticulation(crate::feature::RelativeArticulation::Retracted),
        ),
        (
            "̈",
            RelativeArticulation(crate::feature::RelativeArticulation::Centralized),
        ),
        (
            "̽",
            RelativeArticulation(crate::feature::RelativeArticulation::MidCentralized),
        ),
        (
            "̝",
            RelativeArticulation(crate::feature::RelativeArticulation::Raised),
        ),
        (
            "˔",
            RelativeArticulation(crate::feature::RelativeArticulation::Raised),
        ),
        (
            "̞",
            RelativeArticulation(crate::feature::RelativeArticulation::Lowered),
        ),
        (
            "˕",
            RelativeArticulation(crate::feature::RelativeArticulation::Lowered),
        ),
        (
            "̹",
            RelativeArticulation(crate::feature::RelativeArticulation::OverRounded),
        ),
        (
            "͗",
            RelativeArticulation(crate::feature::RelativeArticulation::OverRounded),
        ),
        (
            "̜",
            RelativeArticulation(crate::feature::RelativeArticulation::UnderRounded),
        ),
        (
            "͑",
            RelativeArticulation(crate::feature::RelativeArticulation::UnderRounded),
        ),
        (
            "ʷ",
            SecondaryArticulation(crate::feature::SecondaryArticulation::Labialized),
        ),
        (
            "ʲ",
            SecondaryArticulation(crate::feature::SecondaryArticulation::Palatalized),
        ),
        (
            "ˠ",
            SecondaryArticulation(crate::feature::SecondaryArticulation::Velarized),
        ),
        (
            "̴",
            SecondaryArticulation(crate::feature::SecondaryArticulation::Velarized),
        ),
        (
            "ˤ",
            SecondaryArticulation(crate::feature::SecondaryArticulation::Pharyngealized),
        ),
        (
            "𐞴",
            SecondaryArticulation(crate::feature::SecondaryArticulation::Epiglottalized),
        ),
        ("̘", TongueRoot(crate::feature::TongueRoot::Advanced)),
        ("̙", TongueRoot(crate::feature::TongueRoot::Retracted)),
        ("̃", Nasalized),
        ("˞", Rhotacized),
        ("ʴ", Rhotacized),
        ("ʵ", Rhotacized),
        ("ʱ", Voice(crate::feature::Voice::Breathy)),
        ("ː", Length(crate::feature::Length::Long)),
        (":", Length(crate::feature::Length::Long)),
        ("̋", Tone(crate::feature::Tone::ExtraHigh)),
        ("́", Tone(crate::feature::Tone::High)),
        ("̄", Tone(crate::feature::Tone::Mid)),
        ("̀", Tone(crate::feature::Tone::Low)),
        ("̏", Tone(crate::feature::Tone::ExtraLow)),
        ("̌", Tone(crate::feature::Tone::Rising)),
        ("̂", Tone(crate::feature::Tone::Falling)),
        ("᷄", Tone(crate::feature::Tone::HighRising)),
        ("᷅", Tone(crate::feature::Tone::LowRising)),
        ("᷈", Tone(crate::feature::Tone::RisingFalling)),
        ("ˑ", Length(crate::feature::Length::HalfLong)),
        ("̆", Length(crate::feature::Length::ExtraShort)),
        ("ʼ", Ejective),
        ("\u{2019}", Ejective), // U+2019 right single quotation mark, sometimes used for ejective
    ]
};

/// See <https://en.wikipedia.org/wiki/Tone_letter>.
pub static TONE_LETTERS: &[(&str, crate::Modifier)] = {
    &[
        // stem to the right
        ("˥", crate::Modifier::Tone(crate::feature::Tone::ExtraHigh)),
        ("˦", crate::Modifier::Tone(crate::feature::Tone::High)),
        ("˧", crate::Modifier::Tone(crate::feature::Tone::Mid)),
        ("˨", crate::Modifier::Tone(crate::feature::Tone::Low)),
        ("˩", crate::Modifier::Tone(crate::feature::Tone::ExtraLow)),
        // stem to the left
        ("꜒", crate::Modifier::Tone(crate::feature::Tone::ExtraHigh)),
        ("꜓", crate::Modifier::Tone(crate::feature::Tone::High)),
        ("꜔", crate::Modifier::Tone(crate::feature::Tone::Mid)),
        ("꜕", crate::Modifier::Tone(crate::feature::Tone::Low)),
        ("꜖", crate::Modifier::Tone(crate::feature::Tone::ExtraLow)),
        // dotted tone letters
        ("꜈", crate::Modifier::Tone(crate::feature::Tone::ExtraHigh)),
        ("꜉", crate::Modifier::Tone(crate::feature::Tone::High)),
        ("꜊", crate::Modifier::Tone(crate::feature::Tone::Mid)),
        ("꜋", crate::Modifier::Tone(crate::feature::Tone::Low)),
        ("꜌", crate::Modifier::Tone(crate::feature::Tone::ExtraLow)),
        // dotted tone letters with stem to the left
        ("꜍", crate::Modifier::Tone(crate::feature::Tone::ExtraHigh)),
        ("꜎", crate::Modifier::Tone(crate::feature::Tone::High)),
        ("꜏", crate::Modifier::Tone(crate::feature::Tone::Mid)),
        ("꜐", crate::Modifier::Tone(crate::feature::Tone::Low)),
        ("꜑", crate::Modifier::Tone(crate::feature::Tone::ExtraLow)),
        // numerals
        ("5", crate::Modifier::Tone(crate::feature::Tone::ExtraHigh)),
        ("4", crate::Modifier::Tone(crate::feature::Tone::High)),
        ("3", crate::Modifier::Tone(crate::feature::Tone::Mid)),
        ("2", crate::Modifier::Tone(crate::feature::Tone::Low)),
        ("1", crate::Modifier::Tone(crate::feature::Tone::ExtraLow)),
        // superscript numerals
        ("⁵", crate::Modifier::Tone(crate::feature::Tone::ExtraHigh)),
        ("⁴", crate::Modifier::Tone(crate::feature::Tone::High)),
        ("³", crate::Modifier::Tone(crate::feature::Tone::Mid)),
        ("²", crate::Modifier::Tone(crate::feature::Tone::Low)),
        ("¹", crate::Modifier::Tone(crate::feature::Tone::ExtraLow)),
    ]
};

pub static CLICKS: &[&str] = &["ʘ", "ǀ", "ǃ", "ǂ", "ǁ", "𝼊", "ʇ", "𝼋", "ʗ", "ʖ"];

pub static IMPLIED_MODIFIERS: phf::Map<&str, &[crate::Modifier]> = {
    use crate::Modifier::*;
    phf::phf_map! {
        "ɚ" | "ɝ" => &[Rhotacized],
        "ɫ" => &[SecondaryArticulation(crate::feature::SecondaryArticulation::Velarized)],
        "ŋ͡ʘ" | "ŋ͡ǀ" | "ŋ͡ǃ" | "ŋ͡ǂ" | "ŋ͡ǁ" |
        "ɴ͡ʘ" | "ɴ͡ǀ" | "ɴ͡ǃ" | "ɴ͡ǂ" | "ɴ͡ǁ" |
        "ŋ͜ʘ" | "ŋ͜ǀ" | "ŋ͜ǃ" | "ŋ͜ǂ" | "ŋ͜ǁ" |
        "ɴ͜ʘ" | "ɴ͜ǀ" | "ɴ͜ǃ" | "ɴ͜ǂ" | "ɴ͜ǁ" |
        "ŋʘ" | "ŋǀ" | "ŋǃ" | "ŋǂ" | "ŋǁ" |
        "ɴʘ" | "ɴǀ" | "ɴǃ" | "ɴǂ" | "ɴǁ" => &[Nasalized]
    }
};
